"""
The `AnyBURL Rule Directory` contains at least the `AnyBURL CW Train Rules TSV` which
contains the rules AnyBURL discovered in the input `AnyBURL CW Train Facts TSV`. The
latter is not generated by AnyBURL automatically but is usually a renamed copy of the
largest rules file output by AnyBURL.

**Structure**

::

    rules/                  # AnyBURL Rules Directory

        cw_train_rules.tsv  # AnyBURL CW Train Rules TSV

|
"""

from pathlib import Path

from data.anyburl.rules.rules_tsv import RulesTsv
from data.base_dir import BaseDir


class RulesDir(BaseDir):
    cw_train_rules_tsv: RulesTsv

    def __init__(self, path: Path):
        super().__init__(path)

        self.cw_train_rules_tsv = RulesTsv(path.joinpath('cw_train_rules.tsv'))

    def check(self) -> None:
        super().check()

        self.cw_train_rules_tsv.check()
